# Code 

In [1]:
import numpy as np
import os

path = os.getcwd() + '/P1_data'
train_data = np.genfromtxt(path +'/P1_data_train.csv', delimiter=',')
label_train = np.genfromtxt(path +'/P1_labels_train.csv', delimiter=',')


data5=[]
data6=[]

#seperating the data from lables
for i in range(777):
    if label_train[i]==5:
        data5.append(train_data[i])
    else:
        data6.append(train_data[i])

mean_5=np.mean(data5,axis=0)
#print mean_5
mean_6=np.mean(data6,axis=0)
#print mean_6

pi_5 = float(len(data5))/777
pi_6 = 1 - pi_5

cov_5 = np.cov(list(map(list, zip(*data5))),ddof=0)
cov_6 = np.cov(list(map(list, zip(*data6))),ddof=0)

inv_cov_5=np.linalg.inv(cov_5)
inv_cov_6=np.linalg.inv(cov_6)

y5 = np.log(pi_5)-0.5*(np.log(np.absolute(np.linalg.det(cov_5))))
y6 = np.log(pi_6)-0.5*(np.log(np.absolute(np.linalg.det(cov_6))))

test_data = np.genfromtxt(path +'/P1_data_test.csv', delimiter=',')
label_test= np.genfromtxt(path + '/P1_labels_test.csv', delimiter=',')

result=np.zeros(len(test_data))
confusion=np.zeros((2,2))

for i in range(int(len(test_data))):
    x=test_data[i]
    r5= -1/2*(np.matmul(x-mean_5,np.matmul(inv_cov_5,x.T-mean_5.T)))+ y5
    r6= -1/2*(np.matmul(x-mean_6,np.matmul(inv_cov_6,x.T-mean_6.T)))+ y6
    if r5>r6:
        result[i]=5
    else:
        result[i]=6
    if label_test[i]==5:
        if result[i]==5:
            confusion[0][0] +=1
        if result[i]==6:
            confusion[1][0] +=1
    if label_test[i]==6:
        if result[i]==5:
            confusion[0][1] +=1
        if result[i]==6:
            confusion[1][1] +=1

#normalizing confusion matrix
confusion/=len(test_data)

Missclassification rate of 5 = 0.198630136986
Missclassification rate of 6 = 0.20320855615
confusion matrix :
[[ 0.35135135  0.08708709]
 [ 0.11411411  0.44744745]]


# Mean of the training data with label 5

In [2]:
mean_5

array([  5.        ,   5.08333333,   8.51515152,  10.34090909,
        10.77272727,   9.58838384,   6.35606061,   4.76767677,
         5.22979798,   6.20959596,  10.78535354,  10.08585859,
         8.82828283,   7.91161616,   5.62373737,   4.69949495,
         4.79040404,   6.82323232,  10.23989899,   7.2020202 ,
         6.05555556,   5.0479798 ,   4.75757576,   4.68686869,
         5.07575758,   6.62878788,  10.51010101,   9.99747475,
         7.99747475,   6.53787879,   4.81313131,   4.71212121,
         5.18686869,   5.71969697,   7.6010101 ,   8.18686869,
         8.88636364,   7.91161616,   5.77777778,   4.43434343,
         4.82323232,   5.15909091,   5.34343434,   6.06313131,
         7.69949495,   8.72474747,   6.16666667,   4.81565657,
         4.56818182,   5.11363636,   7.23989899,   8.01767677,
         9.15909091,   8.12878788,   5.81313131,   4.86616162,
         4.73737374,   5.12626263,   8.96464646,  10.56313131,
         9.06565657,   6.73989899,   5.06818182,   5.24

# Mean of the training data with label 6

In [3]:
mean_6

array([  5.19685039,   5.08923885,   5.95275591,  10.07086614,
         8.56955381,   5.74540682,   5.39632546,   5.02624672,
         4.61154856,   4.97375328,   8.32283465,  10.58005249,
         7.17847769,   5.29133858,   4.86614173,   4.73753281,
         4.93963255,   5.24409449,   9.88976378,   8.76377953,
         4.92913386,   5.02624672,   4.81889764,   5.06036745,
         4.78740157,   5.62729659,  10.93175853,   8.11548556,
         6.48031496,   5.7664042 ,   5.27821522,   4.67454068,
         5.12860892,   6.09448819,  10.7847769 ,   9.76902887,
         9.832021  ,   8.74278215,   5.86351706,   4.81889764,
         5.03674541,   5.8976378 ,  10.7480315 ,   9.26771654,
         7.89501312,   9.59580052,   8.68503937,   4.99475066,
         4.81364829,   5.47506562,   9.34908136,  10.20734908,
         7.49868766,   9.76902887,   9.41994751,   5.10761155,
         4.90551181,   5.05511811,   6.05249344,   9.44094488,
        11.30183727,   9.95538058,   6.66404199,   5.29

# Covariance of training data with label 5

In [4]:
cov_5

array([[ 38.87878788,  21.48484848,  23.59343434, ...,  24.71212121,
         24.8510101 ,  25.71969697],
       [ 21.48484848,  38.50568182,  23.01262626, ...,  27.85248316,
         23.5625    ,  25.52504209],
       [ 23.59343434,  23.01262626,  44.67401286, ...,  23.97237527,
         19.34871442,  26.90159167],
       ..., 
       [ 24.71212121,  27.85248316,  23.97237527, ...,  45.62679191,
         26.25258264,  24.49300454],
       [ 24.8510101 ,  23.5625    ,  19.34871442, ...,  26.25258264,
         39.28575528,  24.95299587],
       [ 25.71969697,  25.52504209,  26.90159167, ...,  24.49300454,
         24.95299587,  41.08393914]])

# Covariance of training data with label 6

In [5]:
cov_6

array([[ 42.92450452,  23.42862752,  25.62609792, ...,  20.85917705,
         24.01364003,  28.49383099],
       [ 23.42862752,  40.29649837,  25.98059396, ...,  25.11684268,
         26.76751331,  27.75090417],
       [ 25.62609792,  25.98059396,  42.79041891, ...,  22.37846942,
         20.9158865 ,  29.15812098],
       ..., 
       [ 20.85917705,  25.11684268,  22.37846942, ...,  40.86152617,
         26.69629584,  22.87389175],
       [ 24.01364003,  26.76751331,  20.9158865 , ...,  26.69629584,
         45.98686975,  26.5309484 ],
       [ 28.49383099,  27.75090417,  29.15812098, ...,  22.87389175,
         26.5309484 ,  42.04373075]])

# Probability of training data with label 5

In [6]:
pi_5

0.5096525096525096

# Probability of training data with label 6

In [7]:
pi_6

0.49034749034749037

# Misclassification rates

In [10]:
print("Missclassification rate of 5 = " + str(confusion[0][1]/(confusion[0][1]+confusion[0][0])))
print("Missclassification rate of 6 = " + str(confusion[1][0]/(confusion[1][1]+confusion[1][0])))

Missclassification rate of 5 = 0.198630136986
Missclassification rate of 6 = 0.20320855615


# Confusion Matrix

In [11]:
confusion

array([[ 0.35135135,  0.08708709],
       [ 0.11411411,  0.44744745]])